### ISSUE TITLE
 Could you please add a readme.md to simply explain how to run this code?

### ISSUE THREAD

**Issue by Elnath-123** [ycWang9725/WSTAN#2]
Thank you for contributing such amazing work, and releasing the source code. Could you please add a readme to simply explain how to run this code?

**Comment by ycWang9725** [comment]
Sorry for late reply.
For now I have little time doing this, and as another issue proposed, some files are missed.
I will spare some time to go through the code and add a readme as soon as possible.

**Comment by fjchange** [comment]
@ycWang9725 

A month passed. Is there any update for the codes?

**Comment by ycWang9725** [comment]
> @ycWang9725
> 
> A month passed. Is there any update for the codes?

Hi, The code & model have been updated in Dec.
